### ISSUE TITLE
Code Redanduncy

### ISSUE THREAD

**Issue by nrfjr** [nrfjr/dbahelp#2]
`<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>`

// Include this code in inc/header.php file so it is loaded in the first place every time a webpage appear. 

//Enough to include it there once for every same type.

**Comment by Kkura02** [comment]
fixed na sir, na butang na nako sa header. og gipangtanggal na nako tong mga redundant , sa akong commit

**Comment by nrfjr** [comment]
`<script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>`

ari pa sir haha
