### ISSUE TITLE
Line Chart Performance

### ISSUE THREAD

**Issue by nrfjr** [nrfjr/dbahelp#3]
- Chart seems to be so lag in the long run.
- Further observation is required.
- Reply on this issue if root cause is found.

**Comment by Kkura02** [comment]
i think adding the resetData Function from our previous line chart is a good idea sir.

**Comment by Kkura02** [comment]
so after researching sir, I found out from this page https://www.amcharts.com/docs/v4/concepts/performance/ that the thing causing high CPU usage and lag from charts is the Animation. 
![image](https://user-images.githubusercontent.com/57450665/201843096-47af4ee4-60d3-491f-8719-1434606479d3.png)


with that note, I did some changes where I disabled the dynamic Animation
![image](https://user-images.githubusercontent.com/57450665/201843262-a694ea7e-4eab-4d1b-a590-9856c48c3a46.png)



thus lowering the cpu usage of my unit, from constant 100% to less than 50%
![image](https://user-images.githubusercontent.com/57450665/201842955-d6345f7c-a776-4f2a-8e86-37a36c8dfe47.png)


I will still be observing it and report it here if I did find some issues.

**Comment by Kkura02** [comment]
> i think adding the resetData Function from our previous line chart is a good idea sir.

 I dont think this is necessary na sir after removing the animation, thou i will let the chart  run as long as it can, and see if it lags.

**Comment by nrfjr** [comment]
i also suspect that aside from animation. maybe it is caused by the realtime data being fed on loop in the background. keep this issue open for a while for further observations. good job!
