### ISSUE TITLE
Separation of js & css.

### ISSUE THREAD

**Issue by nrfjr** [nrfjr/dbahelp#4]
-For Maintenance & Readability Purposes.

**Comment by Kkura02** [comment]
i tried to seperate the js scripts of some sir, but i think the JS scripts that has mixed Php is not possible to separation sir. so today I'll seperate thos pure JS scripts only.

**Comment by Kkura02** [comment]
I tried separating the Script tags  of linecharts and donut charts sir, but after doing it, the chart areas became blank does I came up to conclusion that separating the script tags that includes the chart options and renderers will affect the charts.

**Comment by nrfjr** [comment]
Ok sir, just separate those scripts that does not cause errors for now. thanks.

**Comment by Kkura02** [comment]
Done nako sa pag separate sa CSS scripts sir, sa JS kay I think wala may script tag na dili involve sa charts.
