### ISSUE TITLE
can't log in sir. I tried logging out, but then when I tried to log in, it won't let me in.

### ISSUE THREAD

**Issue by Kkura02** [nrfjr/dbahelp#5]
![image](https://user-images.githubusercontent.com/57450665/201792703-ad22f3e1-b7a2-421e-b305-163c686c87e1.png)

**Comment by Kkura02** [comment]
I tried all account credentials I do have but Its logging me in

**Comment by Kkura02** [comment]
![image](https://user-images.githubusercontent.com/57450665/201794170-0af8d10e-2b0a-4fb9-b363-a33579706d9f.png)
I tried logging in with rms13prd, but this error code displayed

**Comment by nrfjr** [comment]
![FB_IMG_1668466819536.jpg](https://user-images.githubusercontent.com/90370309/201795764-1fe717af-29e8-437d-9d87-94a2dea8948e.jpg)
