### ISSUE TITLE
Slow loading/reloading of web page.

### ISSUE THREAD

**Issue by nrfjr** [nrfjr/dbahelp#6]
The way we set the interval for AJAX every second, i think we are sending far too many HTTP requests too quickly which is flooding our server and also the slow response from database network for every requests might affects this issue. i suggest to set the interval into 15k milliseconds?

**Comment by Kkura02** [comment]
I've set my ajax interval to 15k now sir, but I also tried 10k, then tried to reload it a few times, there are reloading moments where it takes too much time, or glitch appears, In conclusion, I think 15k is now our stable interval for ajax.
