### ISSUE TITLE
the error code is visible when user credentials entered on login is incorrect

### ISSUE THREAD

**Issue by Kkura02** [nrfjr/dbahelp#7]
I'm not sure about this; no error code appears on my end, but Sir Dex reports that it does on his. To elaborate, after Sir Dex attempted to connect to our localhost, He stated that the error code appearing in the login page when incorrect credentials are entered is risky and could lead to data breach. Sir Dex specifically stated that with the error code making an appearance, he can modify the contents of user.php, which is shown in the error code, simply by using SQL inject.

**Comment by Kkura02** [comment]
ow reminder: i just made changes on the config file sir:
![image](https://user-images.githubusercontent.com/57450665/202989049-5d2f1011-ba85-4434-9889-bec84f04cf68.png)
 
 since sir dex and maam mariz cant access our web kanina, he told me to change the word local host to my IP address that is why it is change on my repo, but you dont need to change it on your side sir. Thank you

**Comment by nrfjr** [comment]
What error code they mean is incorrect during login? can you provide screenshot sir?

**Comment by Kkura02** [comment]
> What error code they mean is incorrect during login? can you provide screenshot sir?

unfortunately, I can't provide a Screenshot sir, because the error code only appeared on sir dexter's side, but never on mine. maybe it was just a sham, though I will further observe if it appears again sir.

**Comment by nrfjr** [comment]
We dont have to worry with SQL injection, PDO is what we used for queries and binding parameters and it is more secure as it prepares SQL statements in the first place eliminating quotes and requoting the query. whats more prone to SQL injection is the legacy project or previous project we are getting the ideas as it uses static PL/SQL statements.

**Comment by Kkura02** [comment]
Noted sir, Thank you.

**Comment by nrfjr** [comment]
Diz might help to defend our stand, see top voted answer. https://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection.
and we also sanitize data we get from POST and to think that DBAs are the main user of the system, we can easily suspect who might be using it in the wrong way? (if someone dares to.) #sus #amogus.
