### ISSUE TITLE
Case Sensitivity when logging in credentials

### ISSUE THREAD

**Issue by Kkura02** [nrfjr/dbahelp#8]
Sir, nagmention sila maam mariz and sir dex, na whether small caps daw or big caps ang pag enter sa Username sa login kay dili dw mag matter. Dunno unsa ila pasabot, whether, okay lang ba stay lang tong atoa na dapat na UPPERCASE, or maybe good kung i remove and case sensitivity sa Username. what is your say sir?

**Comment by nrfjr** [comment]
the login system only compares credentials from what exists in the database. there is no case sensivity restriction set for now.

**Comment by Kkura02** [comment]
copy sir.
