### ISSUE TITLE
when searching in manage user

### ISSUE THREAD

**Issue by Kkura02** [nrfjr/dbahelp#9]
![image](https://user-images.githubusercontent.com/57450665/203183787-4c5def06-38ba-4dbf-ae4a-0a3e660bfbfd.png)
this appeared sir, when I tried to search user.

**Comment by nrfjr** [comment]
be on it later. dont sweat it.

**Comment by Kkura02** [comment]
> be on it later. dont sweat it.

no pressure sir :)

**Comment by nrfjr** [comment]
<div class="tenor-gif-embed" data-postid="10843280" data-share-method="host" data-aspect-ratio="1.35326" data-width="100%"><a href="https://tenor.com/view/done-and-done-spongebob-finished-just-did-it-gif-10843280">Done And Done GIF</a>from <a href="https://tenor.com/search/done+and+done-gifs">Done And Done GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by nrfjr** [comment]
https://tenor.com/TEZM.gif

**Comment by nrfjr** [comment]
![done-and-done-spongebob](https://user-images.githubusercontent.com/90370309/203304726-7c3f2ae1-a8b0-43fa-b1cd-8828764e91b4.gif)
